apiVersion: v1
kind: Service
metadata:
  name: dotnet-mysql
  namespace: dotnet
  labels:
    app: dotnet
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30009
  selector:
    app: dotnet
    tier: mysql
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: dotnet
  labels:
    app: dotnet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-mysql
  namespace: dotnet
  labels:
    app: dotnet
spec:
  selector:
    matchLabels:
      app: dotnet
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dotnet
        tier: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

